#!/bin/zsh

# fepper-cli
#
# Based off of grunt-cli, http://gruntjs.com/
# Copyright (c) 2012 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable zsh <tab> completion for Fepper, add the following line (minus the
# leading #, which is the zsh comment character) to your ~/.zshrc file:
#
# eval "$(fepper --completion=zsh)"

# Enable zsh autocompletion.
function _fepper_completion() {
  local completions
  # The currently-being-completed word.
  local cur="${words[@]}"
  # The current Fepper version, available tasks, options, etc.
  local fepperinfo="$(fepper --version --verbose 2>/dev/null)"
  # Options and tasks.
  local opts="$(echo "$fepperinfo" | awk '/Available options: / {$1=$2=""; print $0}')"
  local compls="$(echo "$fepperinfo" | awk '/Available tasks: / {$1=$2=""; print $0}')"
  # Only add -- or - options if the user has started typing -
  [[ "$cur" == -* ]] && compls="$compls $opts"
  # Trim whitespace.
  compls=$(echo "$compls" | sed -e 's/^ *//g' -e 's/ *$//g')
  # Turn compls into an array to of completions.
  completions=(${=compls})
  # Tell complete what stuff to show.
  compadd -- $completions
}

compdef _fepper_completion fepper
